#!/system/bin/sh

# stop ROM VM from booting!
stop;

# set busybox location
BB=/system/xbin/busybox

# export variables for nano
export TERMINFO=/etc/terminfo
export TERM=linux

# remounting rw all partitions
$BB mount -o remount,rw,nosuid,nodev /cache;
$BB mount -o remount,rw,nosuid,nodev /data;
$BB mount -o remount,rw /;
$BB mount -o remount,rw -t auto /system;

$BB ln -s /cust/channel/cn/res /res

# creating temp dir
if [ ! -e /cache/tmp ] 
	then
	$BB mkdir /cache/tmp;	
fi;

$BB ln -s /cache/tmp /tmp;
$BB chmod -R 777 /cache/tmp;
$BB chmod -R 777 /tmp;
$BB chmod 6755 /system/xbin/ext/*;
$BB chmod -R 777 /system/etc/init.d;

# copy cron files
$BB cp -a /res/crontab/ /data/
$BB rm -rf /data/crontab/cron/ > /dev/null 2>&1;
if [ ! -e /data/crontab/custom_jobs ]; then
	$BB touch /data/crontab/custom_jobs;
	$BB chmod 777 /data/crontab/custom_jobs;
fi;

# remount all partitions tweaked settings
for m in $(mount | grep ext[3-4] | cut -d " " -f1); do
	$BB mount -o remount,rw,noatime,nodiratime,noauto_da_alloc,discard,barrier=1 $m;
done;

# cleaning
$BB rm -rf /cache/lost+found/* 2> /dev/null;
$BB rm -rf /data/lost+found/* 2> /dev/null;
$BB rm -rf /data/tombstones/* 2> /dev/null;
$BB rm -rf /data/anr/* 2> /dev/null;
$BB chmod -R 400 /data/tombstones;

# critical Permissions fix
$BB chmod -R 0777 /dev/cpuctl/;
$BB chmod -R 0777 /data/system/inputmethod/;
$BB chown -R root:system /sys/devices/system/cpu/;
$BB chmod -R 0777 /sys/devices/system/cpu/;
$BB chown -R system:system /data/anr;
$BB chmod -R 0777 /data/anr/;
$BB chmod 744 /proc/cmdline;

LOG_SDCARDS=/log-sdcards
FIX_BINARY=/system/bin/fsck_msdos



SDCARD_FIX()
{
	# fixing sdcards
	$BB date > $LOG_SDCARDS;
	$BB echo "FIXING STORAGE" >> $LOG_SDCARDS;

	if [ -e /dev/block/mmcblk1p1 ]; then
		
		# creating sd card size temp file
		if [ ! -e /cache/tmp/sdcard_size ]; then	
			$BB touch /cache/tmp/sdcard_size;	
		fi;
		$BB fdisk -l /dev/block/mmcblk1 | $BB grep Disk| $BB awk '{print $5}'| $BB sed 's/.$//g'| $BB sed 's/\.//g' > /cache/tmp/sdcard_size;

		$BB echo "EXTERNAL SDCARD CHECK" >> $LOG_SDCARDS;
		$BB sh -c "$FIX_BINARY -p -f /dev/block/mmcblk1p1" >> $LOG_SDCARDS;
	else
		$BB echo "EXTERNAL SDCARD NOT EXIST" >> $LOG_SDCARDS;
	fi;

#	$BB echo "INTERNAL SDCARD CHECK" >> $LOG_SDCARDS;
#	$BB sh -c "$FIX_BINARY -p -f /dev/block/mmcblk0p18" >> $LOG_SDCARDS;
#	$BB echo "DONE" >> $LOG_SDCARDS;
}

BOOT_ROM()
{
	# Start ROM VM boot!
	start;

	# start adb shell
	start adbd;
}

BOOT_ROM;
SDCARD_FIX;

